### ISSUE TITLE
Flexit Econordic WH4

### ISSUE THREAD

**Issue by MartinAM80** [sindrebroch/ha-flexit#10]
Hey.

@sindrebroch Maybe you want to make integration with Flexit EcoNordic WH4 Inneklimasetral?

I have it in my house and would like to have more control of it via HA.

Regards,
Martin

**Comment by sindrebroch** [comment]
Have you tried this integration?

**Comment by MartinAM80** [comment]
Yes.
This is what I get:
![image](https://user-images.githubusercontent.com/46328195/140603699-ecdc854d-0901-4472-9513-ee8189c843cd.png)

But Econordic is both, ventilation, water heating and heatpump for floor heating...

**Comment by MartinAM80** [comment]
This is how web control panel overview looks like:

![image](https://user-images.githubusercontent.com/46328195/140603761-c6754517-fe54-41b2-86b1-1e66858b17f2.png)

**Comment by sindrebroch** [comment]
Ah, I understand. 

Seems like a pretty large addition, I think adding it without owning it myself would be pretty difficult. I'll think about it, but I don't think I'll try it anytime soon because of this. Adding new sensors would probably not be too difficult, but new controls might be, because the API can be a little tricky with some things.

You would need to add the specific sensors / entities you would like in the issue, and someone could add it if they feel like it. I think it also would be necessary to add the endpoints from the API, because these would not be visible for people who don't own the unit. 

Pull requests are of course welcome if anyone want to add this functionality, while staying compatible with other units.

**Comment by sindrebroch** [comment]
Closing this issue, because the feature seems out of scope. Of course open for pull request if someone want to do this.
