### ISSUE TITLE
Change Ventilation Mode back to "Calendar"

### ISSUE THREAD

**Issue by ViliusKraujutis** [sindrebroch/ha-flexit#13]
**Is your feature request related to a problem? Please describe.**
Since there's no way to turn "High" ventilation mode "Temporarily", I would like to change it back to the "Calendar" at least manually.

**Describe the solution you'd like**

- I would like to have a functionality to Change Ventilation Mode to "Calendar" which automatically changes modes during the day and night.
- I would like to have a functionality to change Ventilation Mode to "Boost"/"High" with an option "Temporarily"
- There is another mode "Fireplace", which I rarely use, but it would be great to have it available in HA too.

**Describe alternatives you've considered**
I have to turn on the smartphone app to turn back to the "Calendar" mode.

**Additional context**
Attaching couple screenshots from the app's capabilities
![E96EE0F9-A097-47C8-84F0-4D3368DB872C](https://user-images.githubusercontent.com/1859636/144699750-88dbfd7c-5868-462e-83ae-f9720584c67b.PNG)
![0E10ED1C-D019-45A1-9886-49C32F05BD53](https://user-images.githubusercontent.com/1859636/144699753-f4951427-1c74-4e7d-8c2b-261760ed876e.PNG)

**Comment by sindrebroch** [comment]
Hi. Thanks for the feature request. This is something I am already working on, but it requires some rewrites because these endpoints are a bit different that what already exists in the integration. Personally I do my schedule in HomeAssistant, so I guess that is an option if you want, but the Calendar should be available here at some point as well.

**Comment by sindrebroch** [comment]
Should be fixed by [2.2.0](https://github.com/sindrebroch/ha-flexit/releases/tag/2.2.0)
