### ISSUE TITLE
Entities are not listed in Statistics Graph Card Configuration

### ISSUE THREAD

**Issue by mito** [sindrebroch/ha-flexit#30]
Data are pulled and shown in entities card. But not in Statistics Graph Card. Any idea why?

## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by sindrebroch** [comment]
Hmm weird. Does it not work for any of the values? 

If I remember correctly the temperature values should have state_class set, which is the requirement for them to be saved as statistics. Pretty sure this can be added to more of the fields. Any in particular you would like for statistics? 

It has been a while since I looked at it, so some things might have changed.

**Comment by sindrebroch** [comment]
@mito Any in particular you are missing for statistics?

For me some of the values work in the statistics card:
- Temperature Room
- Temperature Outside
- Temperature Supply
- Temperature Exhaust
- Temperature Extract

**Comment by sindrebroch** [comment]
Closing as there is no more info provided
