### ISSUE TITLE
Tested with Nordic S2

### ISSUE THREAD

**Issue by tphakala** [sindrebroch/ha-flexit#7]
Just to comment that this plugin works with my Nordic S2 unit, I can see all values like supply and exhaust temps, fan speeds etc. Mode switching between away, home and boost works, although mode switching does not work from lovelace card icons, I have to go into card properties and switch mode from "Preset" drop down menu.

**Comment by sindrebroch** [comment]
Great to hear. I don't think I have seen Preset-icons in the default thermostat card, is that a feature?

I use [this custom card](https://github.com/nervetattoo/simple-thermostat), so I haven't really tested this.

**Comment by tphakala** [comment]
My Flexit card looks like this, there is icons for fireplace and boost presets.

![image](https://user-images.githubusercontent.com/7030001/133084512-f100dff3-b9e7-4b99-93f7-fce71961f137.png)

But this is not a big issue, since I mainly will operate Flexit in automated manner based on humidity and VOC etc. sensors.

**Comment by sindrebroch** [comment]
Yes, those are the "Operation modes", which are "Fan only" and "Heat". I don't think the stock card shows "Preset modes", which would be "Home", "Away" and "Boost". 

But as your say, these things are fine to automate, and if you want them you can use alternate cards, like the one i linked above :) 

Closing this for now, because I don't think it's a bug with the integration, but instead a missing field in the thermostat-card.
